name: notebooks
channels:
  - conda-forge
dependencies:
  - metview-batch==5.18.0
  - cartopy
  - cfgrib==0.9.10.3
  - cdsapi==0.6.1
  - pip
  - pip:
    - metview==1.13.1
    - scipy
    - matplotlib
    - xarray
    - pandas
    - netcdf4==1.6.3
    - ecmwf-opendata>=0.3.3
    - ecmwf-data
    - magpye==0.1.4
    - ipywidgets
    - ipympl
    - jupyter_contrib_nbextensions
    - jupyterlab
    - nbmake
    - pytest
    - pytest-xdist
    - ecmwf-api-client==1.6.3
